FROM python:3.11.9

# Install necessary Python libraries
RUN pip install pandas

# Set the working directory inside the container
WORKDIR /data

# Command to run Python scripts by default
ENTRYPOINT ["python"]
